baseURL: "/"
defaultContentLanguage: "is"
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
  - sitemap

params:
  google_analytics_id=""

languages:
  is:
    title: "Æskusirkus"
    languageName: "íslensk"
    languageCode: "is"
    weight: 1
    menu:
      main:
      - name: "Um æskusirkusinn"
        url: "/um-aeskusirkusinn/"
        weight: 2
      - name: "Hafa samband"
        url: "/hafa-samband/"
        weight: 3
      - name: "Tenglar"
        url: "/tenglar/"
        weight: 4
      - name: "Skra inn"
        url: "/innri-vefur/"
        identifier: "login-link"
        weight: 5
      - name: "Útskra"
        url: "/"
        identifier: "logout-link"
        weight: 5
      - name: "Sumarnámskeið"
        url: "/sumarnamskeid/"
        weight: 6
      - name: "Vetrarstarf"
        url: "/vetrarstarf/"
        weight: 7
  en:
    title: "Aeskusirkus"
    languageName: "English"
    languageCode: "en-us"
    weight: 2
    menu:
      main:
      - name: "About Aeskusirkus"
        url: "/en/about/"
        weight: 2
      - name: "Contact"
        url: "/en/contact/"
        weight: 3
      - name: "Links"
        url: "/en/links/"
        weight: 4
      - name: "Log In"
        url: "/en/members/"
        identifier: "login-link"
        weight: 5
      - name: "Log Out"
        url: "/"
        identifier: "logout-link"
        weight: 5
      - name: "Summer Classes"
        url: "/en/summer/"
        weight: 6
      - name: "Winter Activities"
        url: "/en/winter/"
        weight: 7
