backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/img/uploaded"
public_folder: "/img/uploaded"
media_library:
  name: cloudinary
  config:
    cloud_name: hringleikur
    api_key: 976281589193922
accept_roles:
  - admin
  - editor
collections:
  - name: "pages"
    label: "Pages"
    t_translations: true # Custom Key
    delete: false
    extension: "yml"
    format: "yml"
    files:
      - label: "Um æskusirkusinn / About"
        name: "um-aeskusirkusinn"
        file: "content/cms/um-aeskusirkusinn.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/about.md"
          - code: is
            file: "content/is/um-aeskusirkusinn.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Banner Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
      - label: "Hafa samband / Contact"
        name: "hafa-samband"
        file: "content/cms/hafa-samband.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/contact.md"
          - code: is
            file: "content/is/hafa-samband.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Banner Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
      - label: "Tenglar / Links"
        name: "tenglar"
        file: "content/cms/tenglar.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/links.md"
          - code: is
            file: "content/is/tenglar.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Banner Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
      - label: "Innri vefur / Members"
        name: "innri-vefur"
        file: "content/cms/innri-vefur/_index.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/members/_index.md"
          - code: is
            file: "content/is/innri-vefur/_index.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Banner Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
      - label: "Fréttir  / News"
        name: "frettir"
        file: "content/cms/innri-vefur/frettir/_index.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/members/news/_index.md"
          - code: is
            file: "content/is/innri-vefur/frettir/_index.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Banner Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
      - label: "Deildir / Disciplines"
        name: "deildir"
        file: "content/cms/innri-vefur/deildir/_index.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/members/disciplines/_index.md"
          - code: is
            file: "content/is/innri-vefur/deildir/_index.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Banner Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
      - label: "Sumarnámskeið / Summer Classes"
        name: "sumarnamskeid"
        file: "content/cms/sumarnamskeid.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/summer.md"
          - code: is
            file: "content/is/sumarnamskeid.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
      - label: "Vetrarstarf / Winter Activities"
        name: "vetrarstarf"
        file: "content/cms/vetrarstarf.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/winter.md"
          - code: is
            file: "content/is/vetrarstarf.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
  - name: "news"
    label: "News"
    folder: "content/cms/news"
    t_languages:
      - code: en
        langIfEmpty: "is"
        folder: "content/en/members/news"
      - code: is
        folder: "content/en/innri-vefur/frettir"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    delete: true
    extension: "yml"
    format: "yml"
    fields:
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD hh:mma"
        required: true
      - label: "Title (Icelandic)"
        name: title_is
        t_root: "title"
        widget: string
        required: true
      - label: "Title (English)"
        name: title_en
        t_root: "title"
        widget: string
        required: false
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Caption (Icelandic)"
        name: caption_is
        t_root: "caption"
        widget: string
        required: false
      - label: "Caption (English)"
        name: caption_en
        t_root: "caption"
        widget: string
        required: false
      - label: "Body (Icelandic)"
        name: "body_is"
        t_root: "body"
        widget: "markdown"
        required: true
      - label: "Body (English)"
        name: "body_en"
        t_root: "body"
        widget: "markdown"
        required: false
