backend:
  name: git-gateway
  branch: master
media_folder: "static/img/uploaded"
public_folder: "/img/uploaded"
t_preprocess_images: true
t_default_image_transformation : strip
media_library:
  name: cloudinary
  config:
    cloud_name: hringleikur
    api_key: 976281589193922
accept_roles:
  - admin
  - editor
collections:
  - name: "Settings"
    label: "Settings"
    delete : false
    extension: "yml"
    format: "yml"
    t_translations : true
    editor:
      preview: false
    files:
      - label: Contact Information
        name: contact
        file: "data/contact.yml"
        fields:
          - label: Email
            name: email
            widget: string
            required: true
          - label: Phone
            name: phone
            widget: string
            required: false
          - label: Address
            name: address
            widget: text
            required: false
      - label: Social Media
        name: social
        file: "data/social.yml"
        fields:
          - label: Twitter
            name: twitter
            widget: string
            required: false
          - label: Instagram
            name: instagram
            widget: string
            required: false
          - label: Facebook
            name: facebook
            widget: string
            required: false
      - label: User Authentication
        name : "auth"
        file : "content/cms/auth.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/auth.md"
          - code: is
            file: "content/is/auth.md"
        fields :
          - label: "Password"
            name: password
            widget: string
            required: true
          - label: "Page Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Page Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Error Message (Icelandic)"
            name: error_is
            t_root: "error"
            widget: string
            required: true
          - label: "Error Message (English)"
            name: error_en
            t_root: "error"
            widget: string
            required: false
          - label: "Button (Icelandic)"
            name: button_is
            t_root: "button"
            widget: string
            required: true
          - label: "Button (English)"
            name: button_en
            t_root: "button"
            widget: string
            required: false
          - label: "Help (Icelandic)"
            name: help_is
            t_root: "help"
            widget: string
            required: true
          - label: "Help (English)"
            name: help_en
            t_root: "help"
            widget: string
            required: false
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
          - name: type
            widget: hidden
      - label: Social Media
        name: social
        file: "data/social.yml"
        fields:
          - label: Twitter
            name: twitter
            widget: string
            required: false
          - label: Instagram
            name: instagram
            widget: string
            required: false
          - label: Facebook
            name: facebook
            widget: string
            required: false
  - name: "pages"
    label: "Pages"
    t_translations: true # Custom Key
    delete: false
    extension: "yml"
    format: "yml"
    files:
      - label: "Heim / Home"
        name: "heim"
        file: "content/cms/_index.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/_index.md"
          - code: is
            file: "content/is/_index.md"
        fields:
          - label: "Banner Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
          - name: type
            widget: hidden
      - label: "Um æskusirkusinn / About"
        name: "um-aeskusirkusinn"
        file: "content/cms/um-aeskusirkusinn.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/about.md"
          - code: is
            file: "content/is/um-aeskusirkusinn.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Banner Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
          - name: type
            widget: hidden
      - label: "Hafa samband / Contact"
        name: "hafa-samband"
        file: "content/cms/hafa-samband.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/hafa-samband.md"
          - code: is
            file: "content/is/hafa-samband.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Banner Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
          - name: type
            widget: hidden
      - label: "Tenglar / Links"
        name: "tenglar"
        file: "content/cms/tenglar.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/links.md"
          - code: is
            file: "content/is/tenglar.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Banner Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
          - name: type
            widget: hidden
      - label: "Innri vefur / Members"
        name: "innri-vefur"
        file: "content/cms/innri-vefur/_index.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/members/_index.md"
          - code: is
            file: "content/is/innri-vefur/_index.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Banner Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
          - name: type
            widget: hidden
          - name: outputs
            widget: hidden
      - label: "Fréttir  / News"
        name: "frettir"
        file: "content/cms/innri-vefur/frettir/_index.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/members/news/_index.md"
          - code: is
            file: "content/is/innri-vefur/frettir/_index.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Banner Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
          - name: type
            widget: hidden
          - name: outputs
            widget: hidden
      - label: "Deildir / Disciplines"
        name: "deildir"
        file: "content/cms/innri-vefur/deildir/_index.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/members/disciplines/_index.md"
          - code: is
            file: "content/is/innri-vefur/deildir/_index.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Banner Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
          - name: type
            widget: hidden
          - name: outputs
            widget: hidden
      - label: "Sumarnámskeið / Summer Classes"
        name: "sumarnamskeid"
        file: "content/cms/sumarnamskeid.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/summer.md"
          - code: is
            file: "content/is/sumarnamskeid.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
          - name: type
            widget: hidden
      - label: "Vetrarstarf / Winter Activities"
        name: "vetrarstarf"
        file: "content/cms/vetrarstarf.yml"
        t_languages: # Custom Key
          - code: en
            langIfEmpty: "is"
            file: "content/en/winter.md"
          - code: is
            file: "content/is/vetrarstarf.md"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: "Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Body (Icelandic)"
            name: "body_is"
            t_root: "body"
            widget: "markdown"
            required: true
          - label: "Body (English)"
            name: "body_en"
            t_root: "body"
            widget: "markdown"
            required: false
          - name: translationKey
            widget: hidden
          - name: layout
            widget: hidden
          - name: date
            widget: hidden
          - name: type
            widget: hidden
  - name: "article"
    label: "News Article"
    folder: "content/cms/innri-vefur/frettir"
    t_translations: true
    t_languages:
      - code: en
        langIfEmpty: "is"
        folder: "content/en/members/news"
      - code: is
        folder: "content/is/innri-vefur/frettir"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    delete: true
    extension: "yml"
    format: "yml"
    identifier_field : "title_is"
    fields:
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD hh:mma"
        required: true
      - label: "Featured"
        name: "featured"
        widget: "boolean"
        default: false
      - label: "Title (Icelandic)"
        name: title_is
        t_root: "title"
        widget: string
        required: true
      - label: "Title (English)"
        name: title_en
        t_root: "title"
        widget: string
        required: false
      - label: "Primary Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Caption (Icelandic)"
        name: caption_is
        t_root: "caption"
        widget: string
        required: false
      - label: "Caption (English)"
        name: caption_en
        t_root: "caption"
        widget: string
        required: false
      - label: "Body (Icelandic)"
        name: "body_is"
        t_root: "body"
        widget: "markdown"
        required: true
      - label: "Body (English)"
        name: "body_en"
        t_root: "body"
        widget: "markdown"
        required: false
      - name: translationKey
        widget: hidden
      - name: layout
        widget: hidden
        default: news
      - name: type
        widget: hidden
        default: news
      - name: outputs
        widget: hidden
        default:
          - html
          - json
  - name: "activity"
    label: "Activity"
    folder: "content/cms/innri-vefur/deildir"
    t_translations: true
    t_languages:
      - code: en
        langIfEmpty: "is"
        folder: "content/en/members/disciplines"
      - code: is
        folder: "content/is/innri-vefur/deildir"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    delete: true
    extension: "yml"
    format: "yml"
    identifier_field : "title_is"
    fields:
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD hh:mma"
        required: true
      - label: "Featured"
        name: "featured"
        widget: "boolean"
        default: false
      - label: "Title (Icelandic)"
        name: title_is
        t_root: "title"
        widget: string
        required: true
      - label: "Title (English)"
        name: title_en
        t_root: "title"
        widget: string
        required: false
      - label: "Primary Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Short Description (Icelandic)"
        name: "description_is"
        t_root: "description"
        widget: "text"
        required: true
      - label: "Short Description (English)"
        name: "description_en"
        t_root: "description"
        widget: "text"
        required: false
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        fields:
          - label: "Title (Icelandic)"
            name: title_is
            t_root: "title"
            widget: string
            required: true
          - label: "Title (English)"
            name: title_en
            t_root: "title"
            widget: string
            required: false
          - label: Image
            name: image
            widget: image
          - label: "Caption (Icelandic)"
            name: caption_is
            t_root: "caption"
            widget: string
            required: false
          - label: "Caption (English)"
            name: caption_en
            t_root: "caption"
            widget: string
            required: false
      - label: "Page Body (Icelandic)"
        name: "body_is"
        t_root: "body"
        widget: "markdown"
        required: true
      - label: "Page Body (English)"
        name: "body_en"
        t_root: "body"
        widget: "markdown"
        required: false
      - name: translationKey
        widget: hidden
      - name: layout
        widget: hidden
        default: discipline
      - name: type
        widget: hidden
        default: discipline
      - name: outputs
        widget: hidden
        default:
          - html
          - json
