backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/img/uploaded"
public_folder: "/img/uploaded"
media_library:
  name: cloudinary
  config:
    cloud_name: hringleikur
    api_key: 976281589193922
accept_roles:
    - admin
    - editor
collections:
  - name: "pages"
    label: "Pages"
    delete: false
    extension: "yml"
    format: "yml"
    files:
      - label: "Um okkur"
        name: "umokkur"
        file: "content/cms/about.yml"
        translations:
          en:
            file: "content/en/about.md"
          is:
            file: "content/is/umokkur.md"
        fields:
          - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma", required: true}
          - {label: "Title (Icelandic)", name: title_is, widget: string, required: true}
          - {label: "Title (English)", name: title_en, widget: string, required: false}
          - {label: "Cover Image", name: "image", widget: "image", required: false}
          - {label: "Caption (Icelandic)", name: caption_is, widget: string, required: false}
          - {label: "Caption (English)", name: caption_en, widget: string, required: false}
          - {label: "Body (Icelandic)", name: "body_is", widget: "markdown", required: true}
          - {label: "Body (English)", name: "body_en", widget: "markdown", required: false}
